server:
  tomcat:
    uri-encoding: UTF-8
  port: 443
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp11ze9wvc5oqf3ov125010.mysql.rds.aliyuncs.com:3306/redcover?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root_chen
    password: Ct981228
#    url: jdbc:mysql://localhost:3306/redcover?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: Ct981228
    hikari:
      # 连接池名
      pool-name: HikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间默认(600000)
      idle-timeout: 180000
      # 最大连接数量 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间(默认半小时:1800000)
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 连接测试的sql语句
      connection-test-query: select 1
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# mybatis-plus 配置



logging:
  level:
    cn.ha5fun.redrecover.mapper: debug
